package git

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/donbowman/github-multi-account-manager/internal/config"
)

// Manager handles git configuration
type Manager struct {
	gitconfig      string
	ghmmConfigsDir string
}

// New creates a new Git manager
func New() (*Manager, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("failed to get home directory: %w", err)
	}

	return &Manager{
		gitconfig:      filepath.Join(home, ".gitconfig"),
		ghmmConfigsDir: home,
	}, nil
}

// UpdateGitconfig updates main .gitconfig with includeIf directives
func (m *Manager) UpdateGitconfig(accounts []config.Account) error {
	const (
		startMarker = "# BEGIN GHMM MANAGED GITCONFIG\n"
		endMarker   = "# END GHMM MANAGED GITCONFIG\n"
	)

	existingContent := ""

	// Read existing config
	if data, err := os.ReadFile(m.gitconfig); err == nil {
		content := string(data)

		// Remove old ghmm section if it exists
		if strings.Contains(content, startMarker) {
			parts := strings.Split(content, startMarker)
			before := parts[0]

			afterParts := strings.Split(content, endMarker)
			after := ""
			if len(afterParts) > 1 {
				after = afterParts[1]
			}

			existingContent = before + after
		} else {
			existingContent = content
		}
	}

	// Generate new includeIf sections
	var newSection strings.Builder
	newSection.WriteString(startMarker)
	newSection.WriteString("# Generated by GitHub Multi-Account Manager\n\n")

	for _, account := range accounts {
		// Ensure directory ends with /
		directory := strings.TrimRight(account.Directory, "/") + "/"
		configFile := fmt.Sprintf("~/.gitconfig-%s", account.Name)

		newSection.WriteString(fmt.Sprintf("# %s account\n", account.Name))
		newSection.WriteString(fmt.Sprintf("[includeIf \"gitdir:%s**\"]\n", directory))
		newSection.WriteString(fmt.Sprintf("    path = %s\n\n", configFile))
	}

	newSection.WriteString(endMarker)

	// Write updated config
	finalContent := strings.TrimRight(existingContent, "\n") + "\n\n" + newSection.String()

	if err := os.WriteFile(m.gitconfig, []byte(finalContent), 0644); err != nil {
		return fmt.Errorf("failed to write gitconfig: %w", err)
	}

	return nil
}

// CreateAccountGitconfig creates a gitconfig file for a specific account
func (m *Manager) CreateAccountGitconfig(account config.Account) error {
	configFile := filepath.Join(m.ghmmConfigsDir, fmt.Sprintf(".gitconfig-%s", account.Name))

	content := fmt.Sprintf(`[user]
    name = %s
    email = %s
    signingkey = %s.pub

[gpg]
    format = ssh
`, account.Username, account.Email, account.SSHKeyPath)

	if err := os.WriteFile(configFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to create account gitconfig: %w", err)
	}

	return nil
}

// RemoveAccountGitconfig removes a gitconfig file for a specific account
func (m *Manager) RemoveAccountGitconfig(accountName string) error {
	configFile := filepath.Join(m.ghmmConfigsDir, fmt.Sprintf(".gitconfig-%s", accountName))

	if err := os.Remove(configFile); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove gitconfig: %w", err)
	}

	return nil
}
