"""Git configuration management for ghmm."""

from pathlib import Path
from typing import List, Tuple


class GitConfigManager:
    """Manages git configuration files."""

    def __init__(self):
        self.gitconfig = Path.home() / ".gitconfig"
        self.ghmm_configs_dir = Path.home()

    def update_gitconfig(self, accounts: List[dict]) -> Tuple[bool, str]:
        """Update main .gitconfig with includeIf directives.
        
        Returns:
            Tuple of (success, message)
        """
        try:
            ghmm_start_marker = "# BEGIN GHMM MANAGED GITCONFIG\n"
            ghmm_end_marker = "# END GHMM MANAGED GITCONFIG\n"
            
            # Read existing config
            existing_content = ""
            if self.gitconfig.exists():
                content = self.gitconfig.read_text()
                
                # Remove old ghmm section if it exists
                if ghmm_start_marker in content:
                    before = content.split(ghmm_start_marker)[0]
                    after_parts = content.split(ghmm_end_marker)
                    after = after_parts[1] if len(after_parts) > 1 else ""
                    existing_content = before + after
                else:
                    existing_content = content
            
            # Generate new includeIf sections
            new_section = ghmm_start_marker
            new_section += "# Generated by GitHub Multi-Account Manager\n\n"
            
            for account in accounts:
                # Ensure directory ends with /
                directory = account['directory'].rstrip('/') + '/'
                config_file = f"~/.gitconfig-{account['name']}"
                
                new_section += f"# {account['name']} account\n"
                new_section += f'[includeIf "gitdir:{directory}**"]\n'
                new_section += f"    path = {config_file}\n\n"
            
            new_section += ghmm_end_marker
            
            # Write updated config
            final_content = existing_content.rstrip() + "\n\n" + new_section
            self.gitconfig.write_text(final_content)
            
            return True, f"Gitconfig updated with {len(accounts)} account(s)"
        except Exception as e:
            return False, f"Failed to update gitconfig: {str(e)}"

    def create_account_gitconfig(self, account: dict) -> Tuple[bool, str]:
        """Create a gitconfig file for a specific account.
        
        Returns:
            Tuple of (success, message)
        """
        try:
            config_file = self.ghmm_configs_dir / f".gitconfig-{account['name']}"
            
            content = f"""[user]
    name = {account['username']}
    email = {account['email']}
    signingkey = {account['ssh_key_path']}.pub

[gpg]
    format = ssh
"""
            
            config_file.write_text(content)
            
            return True, f"Created gitconfig for {account['name']} at {config_file}"
        except Exception as e:
            return False, f"Failed to create account gitconfig: {str(e)}"

    def remove_account_gitconfig(self, account_name: str) -> Tuple[bool, str]:
        """Remove a gitconfig file for a specific account.
        
        Returns:
            Tuple of (success, message)
        """
        try:
            config_file = self.ghmm_configs_dir / f".gitconfig-{account_name}"
            
            if config_file.exists():
                config_file.unlink()
                return True, f"Removed gitconfig for {account_name}"
            else:
                return True, "Gitconfig file not found (already removed)"
        except Exception as e:
            return False, f"Failed to remove gitconfig: {str(e)}"
