"""Shell configuration management for ghmm."""

import os
import subprocess
from pathlib import Path
from typing import Optional, Tuple


class ShellManager:
    """Manages shell configuration files."""

    SUPPORTED_SHELLS = {
        "zsh": ".zshrc",
        "bash": ".bashrc",
        "fish": ".config/fish/config.fish",
    }

    def __init__(self):
        self.shell_type = self.detect_shell()
        self.config_file = self.get_config_file()

    def detect_shell(self) -> str:
        """Detect the current shell."""
        shell = os.environ.get("SHELL", "")
        
        if "zsh" in shell:
            return "zsh"
        elif "bash" in shell:
            return "bash"
        elif "fish" in shell:
            return "fish"
        else:
            # Default to bash
            return "bash"

    def get_config_file(self) -> Path:
        """Get the config file path for the current shell."""
        config_name = self.SUPPORTED_SHELLS.get(self.shell_type, ".bashrc")
        return Path.home() / config_name

    def generate_gclone_function(self, accounts: list, default_account: Optional[str] = None) -> str:
        """Generate the smart gclone function for shell."""
        
        if self.shell_type == "fish":
            return self._generate_fish_function(accounts, default_account)
        else:
            return self._generate_posix_function(accounts, default_account)

    def _generate_posix_function(self, accounts: list, default_account: Optional[str] = None) -> str:
        """Generate gclone function for bash/zsh."""
        
        # Build the case statement for directory mapping
        case_statements = []
        default_host = "github.com"
        
        for account in accounts:
            directory = account['directory']
            host_alias = account['host_alias']
            name = account['name']
            
            # Determine if this is the default
            is_default = (default_account == name) if default_account else False
            if is_default:
                default_host = host_alias
            
            case_statements.append(f"""        *{directory}*)
            host="{host_alias}"
            echo "🔑 Cloning with {name} account..."
            ;;""")
        
        cases = "\n".join(case_statements)
        
        function = f"""
# Smart git clone - automatically uses the right GitHub account
# Generated by GitHub Multi-Account Manager (ghmm)
alias gclone='_smart_clone'

_smart_clone() {{
    local repo_url="$1"
    
    if [[ -z "$repo_url" ]]; then
        echo "Usage: gclone <github-url>"
        return 1
    fi
    
    # Extract owner/repo from various URL formats
    local owner_repo=""
    if [[ $repo_url =~ github\\.com[:/]([^/]+/[^/]+)(\\.git)?$ ]]; then
        owner_repo="${{BASH_REMATCH[1]%.git}}"
    elif [[ $repo_url =~ ^([^/]+/[^/]+)$ ]]; then
        owner_repo="$repo_url"
    else
        echo "Invalid GitHub URL. Supported formats:"
        echo "  - https://github.com/owner/repo"
        echo "  - git@github.com:owner/repo.git"
        echo "  - owner/repo"
        return 1
    fi
    
    # Determine which host to use based on current directory
    local host="{default_host}"
    case "$PWD" in
{cases}
        *)
            echo "👤 Cloning with default account..."
            ;;
    esac
    
    git clone "git@${{host}}:${{owner_repo}}.git"
}}
"""
        return function

    def _generate_fish_function(self, accounts: list, default_account: Optional[str] = None) -> str:
        """Generate gclone function for fish shell."""
        
        # Build the switch statement for directory mapping
        case_statements = []
        default_host = "github.com"
        
        for account in accounts:
            directory = account['directory']
            host_alias = account['host_alias']
            name = account['name']
            
            is_default = (default_account == name) if default_account else False
            if is_default:
                default_host = host_alias
            
            case_statements.append(f"""        case '*{directory}*'
            set host "{host_alias}"
            echo "🔑 Cloning with {name} account..."
""")
        
        cases = "\n".join(case_statements)
        
        function = f"""
# Smart git clone - automatically uses the right GitHub account
# Generated by GitHub Multi-Account Manager (ghmm)
function gclone
    set repo_url $argv[1]
    
    if test -z "$repo_url"
        echo "Usage: gclone <github-url>"
        return 1
    end
    
    # Extract owner/repo from various URL formats
    set owner_repo ""
    if string match -qr 'github\\\\.com[:/]([^/]+/[^/]+)(\\\\.git)?\\$' $repo_url
        set owner_repo (string replace -r '\\\\.git\\$' '' (string match -r 'github\\\\.com[:/]([^/]+/[^/]+)' $repo_url)[2])
    else if string match -qr '^[^/]+/[^/]+\\$' $repo_url
        set owner_repo $repo_url
    else
        echo "Invalid GitHub URL. Supported formats:"
        echo "  - https://github.com/owner/repo"
        echo "  - git@github.com:owner/repo.git"
        echo "  - owner/repo"
        return 1
    end
    
    # Determine which host to use based on current directory
    set host "{default_host}"
    switch $PWD
{cases}        case '*'
            echo "👤 Cloning with default account..."
    end
    
    git clone "git@$host:$owner_repo.git"
end
"""
        return function

    def update_shell_config(self, accounts: list, default_account: Optional[str] = None) -> Tuple[bool, str]:
        """Update shell config with gclone function.
        
        Returns:
            Tuple of (success, message)
        """
        try:
            ghmm_start_marker = "# BEGIN GHMM SMART CLONE\n"
            ghmm_end_marker = "# END GHMM SMART CLONE\n"
            
            # Read existing config
            existing_content = ""
            if self.config_file.exists():
                content = self.config_file.read_text()
                
                # Remove old ghmm section if it exists
                if ghmm_start_marker in content:
                    before = content.split(ghmm_start_marker)[0]
                    after_parts = content.split(ghmm_end_marker)
                    after = after_parts[1] if len(after_parts) > 1 else ""
                    existing_content = before + after
                else:
                    existing_content = content
            
            # Generate new function
            gclone_function = self.generate_gclone_function(accounts, default_account)
            new_section = ghmm_start_marker + gclone_function + ghmm_end_marker
            
            # Write updated config
            final_content = existing_content.rstrip() + "\n\n" + new_section
            self.config_file.write_text(final_content)
            
            return True, f"{self.shell_type} config updated at {self.config_file}"
        except Exception as e:
            return False, f"Failed to update shell config: {str(e)}"

    def get_reload_command(self) -> str:
        """Get the command to reload shell config."""
        return f"source {self.config_file}"
